name: auto-build

on: push

jobs:
  build:
    runs-on: self-hosted
    container:
        image: turbograph-s62-0727:latest
        options: --shm-size=256g
        volumes:
          - /mnt/sde/jhha_ldbc/tbgppv3-data:/data
          - /mnt/sde/source-data:/source-data
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Print git log
      run: git log

    - name: Get commit branch and commit message
      if: github.event_name == 'push'
      run: |
        echo "COMMIT_BRANCH=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV
        echo "COMMIT_MESSAGE<<EOF" >> $GITHUB_ENV
        echo "$(git log --format=%B -n 1 HEAD)" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
    
    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake -GNinja -DCMAKE_BUILD_TYPE=Debug ..
        ninja
